/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/libroRosso.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Model = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/libroRosso.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="book_animated" position={[-0.052, 0.716, 0.065]} rotation={[Math.PI, 0, -1.814]} scale={0.142}>
          <group name="Armature" position={[0.493, -0.075, 0.736]}>
            <primitive object={nodes.Bone} />
            <group name="Plane001">
              <skinnedMesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.cover} skeleton={nodes.Plane001_1.skeleton} />
              <skinnedMesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.inner} skeleton={nodes.Plane001_2.skeleton} />
            </group>
            <group name="Plane004">
              <skinnedMesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials.side} skeleton={nodes.Plane007_1.skeleton} />
              <skinnedMesh name="Plane007_2" geometry={nodes.Plane007_2.geometry} material={materials.page} skeleton={nodes.Plane007_2.skeleton} />
            </group>
            <group name="Plane005">
              <skinnedMesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials.side} skeleton={nodes.Plane004_1.skeleton} />
              <skinnedMesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials.page} skeleton={nodes.Plane004_2.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/libroRosso.glb')

export default Model;
